name: Deploy website

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install & Build
        run: |
           pip install -r cookbook/requirements.txt
           make run-scraping
           mkdocs gh-deploy --force
