name: Deploy website

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install 
        run: |
          pip install -r cookbook/requirements.txt
      - name: Scrape
        run: |
          make run-scraping
      - name: Build
        run: |
          mkdocs gh-deploy --force
